@startuml
title クラス図
package Interface {
	interface Initialization{
		+virtual void Initialize() = 0
		+virtual void Finalize() = 0
	}

	interface Activity {
		+virtual void Update() = 0
		+virtual void Draw() = 0
	}
}

package Vector {
	class Vector2D {
		#double StartX
		#double StartY
		#double ComponentX
		#double ComponentY
		+Vector2D()
		+Vector2D(double StartX, double StartY)
		+double GetVectorMagnitude()
		+void SetStartPoint(double StartX, double StartY)
		+void SetStartPoint(Vector2D Vector)
		+void SetEndPoint(double EndX, double EndY)
		+void SetEndPoint(Vector2D Vector)
		+void SetComponent(double ComponentX, double ComponentY)
		+void SetPolarForm(double Angle, double Magnitude)
		+void SetAngle(double Angle)
		+void SetMagnitude(double Magnitude)
		+void AddAngle(double Angle)
		+void AddMagnitude(double Magnitude)
		+void GetStartPoint(double *StartX, double *StartY);
		+void GetEndPoint(double *StartX, double *StartY)
		+void GetComponent(double *ComponentX, double *ComponentY)
		+double GetAngle();
		+virtual double GetMagnitude()
		+Vector2D GetVectorToVector(Vector2D Vector)
		+Vector2D GetVectorStartPointToEndPoint(Vector2D Vector)
		+Vector2D GetVectorEndPointToEndPoint(Vector2D Vector)
		+Vector2D operator + (Vector2D Vector)
		+Vector2D operator - (Vector2D Vector)
		+Vector2D operator * (double Value)
		+Vector2D operator / (double Value)
		+void operator += (Vector2D Vector)
		+void operator -= (Vector2D Vector)
		+void operator *= (double Value)
		+void operator /= (double Value)
		+virtual void Update()
		+virtual void Draw()
	}

	class Vector3D {
		#double StartZ
		#double ComponentZ
		+void SetVectorComponent(double ComponentX, double ComponentY, double ComponentZ)
		+Vector3D GetTargetPointVector(Vector3D Vector)
		+void GetVectorComponent(double *ComponentX, double *ComponentY, double *ComponentZ)
		+void GetStartPoint(double *StartX, double *StartY, double *StartZ);
		+void Draw()
	}

	Activity <|--- Vector2D
	Vector2D <|-- Vector3D
}

package Sprite {
	enum MoveType {
		+MoveType_Accelerate1
		+MoveType_Accelerate2
		+MoveType_Accelerate3
		+MoveType_Uniform
		+MoveType_Decelerate1
		+MoveType_Decelerate2
		+MoveType_Decelerate3
	}

	class Sprite {
		#Vector2D MoveVector
		#Timer DelayTimer
		+void Move()
		+void MoveToPoint(double X, double Y, MoveType MoveType, int DelayTime)
		+void Stop()
		+Vector2D GetVector()
		+virtual void Initialize()
		+virtual void Finalize()
		+virtual void Update()
		+virtual void Draw()
	}

	Initialization <|--- Sprite
	Activity <|--- Sprite
}

package Dialog {
	enum ButtonState {
		+Off
		+On
		+Hover
	}

	enum DialogIcon {
		+Information
		+Question
		+Exclamation
		+Error
		+Wait
		+None
	}

	class Dialog {
		#StringResource Message
		#DialogIcon Icon
		#DefaultButton
		#bool Active
		#void ButtonDraw(std::string Message, ButtonState State)
		+Dialog()
		+Dialog(std::string Text)
		+void Initialize()
		+void Initialize(StringResource Message, DialogIcon Icon, DefaultButton)
		+void Finalize()
		+void Show()
		+void Hide()
		+void Update()
		+virtual void Draw()
	}

	class OKDialog {
		#bool Decide
		+void Draw()
	}

	class TimerDialog {
		#Timer Timer
		+void SetHideTime(double Time)
	}

	class YesNoDialog {
		#int Cursor
		+void SetDefaultState()
		+int GetSelectState()
		+void Draw()
	}

	class WordDialog {
		+void Draw()
	}

	class ResolutionChangeDialog {
		+void Draw()
	}

	Initialization <|--- Dialog
	Activity <|--- Dialog
	Dialog <|-- TimerDialog
	Dialog <|-- OKDialog
	Dialog <|-- YesNoDialog
	TimerDialog <|-- WordDialog
	TimerDialog <|-- ResolutionChangeDialog
	YesNoDialog <|-- ResolutionChangeDialog
}

package Timer {
	enum CountMode {
		+CountUp
		+CountDown
		+Loop
	}

	class Timer {
		#int Value
		#int DefaultValue
		#bool Active
		#bool CountDown
		#bool Loop
		+Timer()
		+Timer(int Value)
		+Timer(double Second)
		+Timer(int Value, CountMode CountMode)
		+Timer(double Second, CountMode CountMode)
		+void SetValue(int Value)
		+void SetSecond(double Second)
		+void SetDefaultValue(int Value)
		+void SetCountMode(CountMode Mode)
		+void EnableCountLoop(bool Flag)
		+int GetValue()
		+double GetSecond()
		+int GetDefaultValue()
		+void Start()
		+void Stop()
		+void Reset()
		+void Update()
		+virtual void Draw()
	}

	class BossTimer {
		+void Draw()
	}

	class SelectTimer {
		+void Draw()
		+void Draw(int X, int Y)
	}

	Activity <|--- Timer
	Timer <|-- BossTimer
	Timer <|-- SelectTimer
}

package Pad {
	enum ButtonAssign {
		Shot
		Bomb
		Laser
		Possess
		Pause
		Credit
		Service
		TotalNum
	}

	enum DPadAssign {
		Up
		Down
		Left
		Right
		TotalNum
	}

	enum DirectInputDPadAssign {
		XAxis
		YAxis
		ZAxis
		XRota
		YRota
		ZRota
		POV1
		POV2
		POV3
		POV4
		None
	}

	enum XInputDPadAssign {
		LeftStick
		RightStick
		DPad
		None
	}

	class Pad {
		#int PadNumber
		#bool Vibration
		#int KeyInputButtonAssign[ButtonAssign.TotalNum]
		#int XInputButtonAssign[ButtonAssign.TotalNum]
		#int DirectInputButtonAssign[ButtonAssign.TotalNum]
		#int KeyInputDPadAssign[DPadAssign.TotalNum]
		#DirectInputDPadAssign DirectInputDPadAssign[DPadAssign.TotalNum][3]
		#XInputDPadAssign XInputDPadAssign[3]
		+void SetButtonAssign(ButtonAssign Assign)
		+void Initialize()
		+void Finalize()
		+void Update()
		+void Draw()
	}

	Initialization <|--- Pad
	Activity <|--- Pad
}

package Player {
	class Player {
		#Timer InvincibleTime
		+void Initialize()
		+void Finalize()
		+void Update()
		+void Draw()
	}

	Sprite <|-- Player
}

package Enemy {
	class Enemy {
		#int HP
		#Timer Timer
	}

	class BossEnemy {
		#BossTimer Timer
	}

	Sprite <|-- Enemy
	Enemy <|-- BossEnemy
}

package Bullet {
	enum PlayerBulletType {

	}

	enum EnemyBulletType {

	}

	class Bullet {
		#double Angle
		#double Speed
		+void Update()
	}

	class PlayerBullet {
		+void Draw()
	}

	class EnemyBullet {
		+void Draw()
	}

	Sprite <|-- Bullet
	Bullet <|-- PlayerBullet
	Bullet <|-- EnemyBullet
}

package Scene {
	enum PlayerCharacter {
	}

	class Scene {
		#Pad Pad[2]
		+virtual void Initialize()
		+virtual void Finalize()
		+virtual void Update()
		+virtual void Draw()
	}

	Scene <|-- Title
	Scene <|-- Menu
	Scene <|-- Option
	Initialization <|--- Scene
	Activity <|--- Scene
}

package Game {
	enum GameMode {
		+GameMode_Arcade
		+GameMode_Novice
		+GameMode_BossRush
		+GameMode_
	}

	object ReplayHeader <<struct>> {
		+PlayerCharacter Player[2]
		+Name
		+Stage
		+
	}

	object PadInputState <<struct>> {
		+ButtonAssign Button
		+DPadAssign DPad
		+int PressStartFrame
		+unsigned short PressFrameLength
	}

	class Game {
		#Timer FrameTimer
		#Player Player
		#StringResource CharacterWord
		+virtual void Update()
		+virtual void Draw()
	}

	class Replay {
		#std::vector<PadInputState> Data
	}

	Scene <|-- Game
	Game <|-- StoryPlayback
	Game <|-- GameTitle
	Game <|-- Ranking
	Game <|-- CharacterSelect
	Game <|-- Instruction
	Game <|-- MainGame
	Game <|-- NameEntry
	MainGame <|-- Replay
	Replay <|-- Demonstration
}

package StringResource {
	enum Language {
		+Japanese
		+English
	}

	class StringResource {
		#std::string String
		+std::string SetString(Language Language, char *String)
		+std::string GetString()
		+std::string GetString(Language Language)
		+void Initialize()
		+void Finalize()
	}

	Initialization <|--- StringResource
}

package CoinChute {
	class CoinChute {
		#unsigned int Coin
		#unsigned int Credit
		#int NeedsCoinToCredit
		+CoinChute()
		+CoinChute(int NeedCoinToCredit)
		+~CoinChute()
		+void SetNeedCoinTo1Credit(int Coin)
		+void UseCredit()
		+void AddCoin()
		+bool GetFreePlayFlag()
		+unsigned int GetCoin()
		+unsigned int GetCredit()
		+unsigned int GetNeedStartCoin()
		+int GetNeedCoinTo1Credit()
		+void Initialize()
		+void Finalize()
	}

	Initialization <|--- CoinChute
}
@enduml