@startuml
title クラス図
package Interface {
	interface ObjectInterface{
		+virtual void Initialize() = 0
		+virtual void Finalize() = 0
	}

	interface Activity {
		+virtual void Update() = 0
		+virtual void Draw() = 0
	}
}

ObjectInterface <|-- Figure

Activity <|-- Dialog
Activity <|-- Timer
Activity <|-- Figure
Activity <|-- Scene

package Figure {
	class Figure {
		#double X
		#double Y
		+void Move(double X, double Y)
		+virtual void Update()
	}
}

package Dialog {
	class Dialog {
		#std::string Message
		#bool Active
		#void ButtonDraw(std::string Text)
		+Dialog()
		+Dialog(std::string Text)
		+~Dialog()
		+void Show()
		+void Hide()
		+void Update()
		+virtual void Draw()
	}

	class OKDialog {
		#bool Decide
		+void Draw()
	}

	class TimerDialog {
		#Timer Timer
		+void SetHideTime(double Time)
	}

	class YesNoDialog {
		#int Cursor
		+void SetDefaultState()
		+int GetSelectState()
		+void Draw()
	}

	class WordDialog {
		+void Draw()
	}

	class ResolutionChangeDialog {
		+void Draw()
	}

	Dialog <|-- TimerDialog
	Dialog <|-- OKDialog
	Dialog <|-- YesNoDialog
	TimerDialog <|-- WordDialog
	TimerDialog <|-- ResolutionChangeDialog
	YesNoDialog <|-- ResolutionChangeDialog
}

package Timer {
	enum CountMode {
		+CountUp
		+CountDown
		+Loop
	}

	class Timer {
		#int Value
		#int DefaultValue
		#bool Active
		#bool CountDown
		#bool Loop
		+Timer()
		+Timer(int Value)
		+Timer(double Second)
		+Timer(int Value, CountMode CountMode)
		+Timer(double Second, CountMode CountMode)
		+void SetValue(int Value)
		+void SetSecond(double Second)
		+void SetDefaultValue(int Value)
		+void SetCountMode(CountMode Mode)
		+void EnableCountLoop(bool Flag)
		+int GetValue()
		+double GetSecond()
		+int GetDefaultValue()
		+void Start()
		+void Stop()
		+void Reset()
		+void Update()
		+virtual void Draw()
	}

	class BossTimer {
		+void Draw()
	}

	class SelectTimer {
		+void Draw()
		+void Draw(int X, int Y)
	}

	Timer <|-- BossTimer
	Timer <|-- SelectTimer
}

package Player {
	class Player {
		#Timer InvincibleTime
		+void Initialize()
		+void Finalize()
		+void Update()
		+void Draw()
	}

	Figure <|-- Player
}

package Enemy {
	class Enemy {
		#int HP
		#Timer Timer
	}

	class BossEnemy {
		#BossTimer Timer
	}

	Figure <|-- Enemy
	Enemy <|-- BossEnemy
}

package Bullet {
	enum PlayerBulletType {

	}

	enum EnemyBulletType {

	}

	class Bullet {
		#double Angle
		#double Speed
		+void Update()
	}

	class PlayerBullet {
		+void Draw()
	}

	class EnemyBullet {
		+void Draw()
	}

	Figure <|-- Bullet
	Bullet <|-- PlayerBullet
	Bullet <|-- EnemyBullet
}

package Scene {
	class Scene {
		-int Oppai
		+int GetSize()
	}
}

package StringResource {
	enum Language {
		+Japanese
		+English
	}

	class StringResource {
		#std::string Text
		+std::string GetString(Language Language)
	}
}
@enduml